### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by EdwardChamberlain** [marcolagi/quantulum#16]
When importing the module I get the following syntax error:

```
>>> from quantulum import parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/quantulum/parser.py", line 124
    value = re.sub(ur'(?<=\d)(%s)10' % r.MULTIPLIERS, 'e', value)
                                   ^
SyntaxError: invalid syntax
```

**Comment by EdwardChamberlain** [comment]
Assumed to be python2 issue

**Comment by parthushah8** [comment]
Hey @EdwardChamberlain how did you resolve it? I work with Python3 and even then the error is popping up.

**Comment by EdwardChamberlain** [comment]
> Hey @EdwardChamberlain how did you resolve it? I work with Python3 and even then the error is popping up.

I cannot remember how I resolved it - make sure you install with pip3 and are using python3 (not pip or python and check the version of both).
